- name: Control play books using ansible facts 
  hosts: frontend
  become: yes
  tasks:
  - name: Install Nginx if OS is RedHat
    ansible.builtin.dnf:
      name: nginx 
      state: present
    when: ansible_os_family == "RedHat"

  - name: Install Nginx if OS is Debian
    ansible.builtin.apt:
      name: nginx
      state: present
    when: ansible_os_family == "Debian"      